### PR TITLE
Gateway: Page to bridge to Alt L1 

### PR DESCRIPTION
**Pull request by sk-enya**
:clipboard: Add associated issues, tickets, docs URL here.

closes: https://github.com/bobanetwork/gateway/issues/28

### Alt L1 Bridging Feature (Internal Use Only)

You can access the page on [Alt L1 bridging link](https://staging.gateway.boba.network/altbridge)

## Changes
Screenshot 2023-09-30 at 10 22 12 AM
Screenshot 2023-09-30 at 10 22 17 AM
Screenshot 2023-09-30 at 10 22 25 AM
Screenshot 2023-09-30 at 10 22 31 AM

### CODE REVIEW

**Comment by sk-enya** [comment]
Shipping changes from same branch to staging environment for testing!

**Comment by wsdt** [comment]
Looks like we get rate limited for CoinGecko's API: 
image

**Comment by sk-enya** [comment]
> Looks like we get rate limited for CoinGecko's API: image

To me it seems the CORS issue is CoinGecko's not allowing request from localhost. 

As it's seems console is clean while accessing the same from 
https://staging.gateway.boba.network/altbridge

**Comment by alvaro-ricotta** [comment]
Pretty small things:
1) Is it not a good idea to sort the tokens based on whether or not they have the ability to bridge? Currently, the only option is BOBA; what sense does it make to show it in the middle of the list if, for now, it's the only one you can interact with?
2) Nothing to bridge modal doesn´t work fine. it at top left. 
3) If user have no available funds to swap, should we show the modal? or just hide the button?
4) fix the text size,, please use same font size as other pages/tables

**Comment by sk-enya** [comment]
Thank you,  @alvaro-ricotta - I appreciate your review.

I added a fix for the 2/ and 4/.
But I don't think it makes to spend more time on this as anyhow this page is going to be removed soon with teleportation and not available for user to access easily as far as you know the url.

Purpose of implementing this is to make the alt l1 bridging feature to be enable for internal USE

**Comment by sk-enya** [comment]
Not for merge, as changes are only prepare to get the feature up for internal purpose.

**Comment by sk-enya** [comment]
Closing as not relevant any more, can open back whenever needed!

**Pull request closed without merging**
