### PR TITLE
Hooks - useWalletSwitch- unit tests

### PR DESCRIPTION
**Pull request by alvaro-ricotta**
## Changes
Unit test for accountEnabled null on useWalletSwitch
Unit test for switch network modal

image

### CODE REVIEW

**Review by sk-enya — CHANGES_REQUESTED** [review]
let's try to improve the coverage to 90%

**Comment by sk-enya** [comment]
@alvaro-ricotta please make sure to follow the pull request template as we have do not remote it.

**Comment by alvaro-ricotta** [comment]
> let's try to improve the coverage to 90%

image

**Comment by sk-enya** [comment]
Just updated the test cases with 100% coverage.
Screenshot 2023-11-11 at 2 19 02 PM


All good now we are good to merge!

**Review by sk-enya — APPROVED** [review]
Good Job!

**Pull request merged**
