### PR TITLE
Fix/crashes and anchorage withdrawal

### PR DESCRIPTION
**Pull request by sk-enya**
Fix/crashes and anchorage withdrawal

Changes:
---
- invoke boba fee choice for only bnb mainnet
- wait on time for btn enable on withdrawal light bridge
- updated the readme for configuration.

Changes:
---
- change: latest L2output block fetching to oracle service.
- change: useAnchorageWithdrawal as separate hook
- change to remove the MM add network warning!
- Fetch block number from diputeGameFactory contract 
- update copy incase of fruad proof withdrawal enable 
- useAppConfig hook to handled app related configuration!.
- provetransaction withdrawal for fruad proof service function with action to trigger. 
- checkWithdrawal with op_portal2 contract 
- withdrawal finalize status call from services to enable button. 
- hardcoded address for sepolia op portal2 with note.

TODO: Before Merging make sure to merge graphql utils 
https://github.com/bobanetwork/graphql-utils/pull/6

- [x] publish latest graphql utils changes PR https://github.com/bobanetwork/graphql-utils/pull/6
- [x] Updated graphql version in gateway under current PR.

### CODE REVIEW

**Review by wsdt — APPROVED** [review]

**Comment by boyuan-chen** [comment]
@sk-enya Why are the end-to-end tests disabled?
``
on: 
  # push: 
  #   branches: ['main', 'master']
  # pull_request:
  workflow_dispatch
```

**Comment by sk-enya** [comment]
> @sk-enya Why are the end-to-end tests disabled?
> 
> ```
> on: 
>   # push: 
>   #   branches: ['main', 'master']
>   # pull_request:
>   workflow_dispatch
> ```

It's not disabled setup to work on dispatch so we have to trigger it manually so we can run it on demand instead of every push to avoid the draining of funds from test account!

**Comment by boyuan-chen** [comment]
> > @sk-enya Why are the end-to-end tests disabled?
> > ```
> > on: 
> >   # push: 
> >   #   branches: ['main', 'master']
> >   # pull_request:
> >   workflow_dispatch
> > ```
> 
> It's not disabled setup to work on dispatch so we have to trigger it manually so we can run it on demand instead of every push to avoid the draining of funds from test account!

I have a lot of ETH. Could you enable the test and let me know the address?

**Comment by sk-enya** [comment]
Sure!

**Review by boyuan-chen — APPROVED** [review]

**Pull request merged**
