### PR TITLE
Package: Anchorage & Light Bridge Crash Fixes.

### PR DESCRIPTION
**Pull request by sk-enya**
:clipboard:  closes: 

## Changes
--- 
 - Light Bridge Fee 1% hardcoded to be show on UI with amount to to recieve.
 - Remove Verifier for ethereum
 - Recurssively loading of tx on history page fix.
 - Fix bridging success modal modal.
 - State handling in case of 2 step withdrawal new and old tx.
 - Proof withdrawal button to enabled based on comparision of latest block sumbitted block and also updated copy.
 - Disable claim button for 7 days after claim withdrawal.
 - Update message copy for claim funds before 7days and after 7days has been passed.
 - Legacy ETH token check and parsing fixes till 1st of may.
 - Light bridge - MaxDaily limit, Time stamp check on, removed unused alert code.
 - Updated tests
 - Fixes for Crashes on history and bridge page

### Checklist Validate on Staging.
- [x]  Classic bridging - ETH deposit and withdrawal (until msg proving) works on staging mainnet
- [x]  Classic bridging - BOBA deposit and withdrawal (until msg proving) works on staging mainnet
- [x]  Classic bridging - ETH and BOBA succesful withdrawal works on testnet (to avoid withdrawal period)
- [x]  Light bridging - $ETH can be bridged between Ethereum <> Boba ETH (both ways) on staging mainnet
- [x]  Light bridging - $BOBA can be bridged between Ethereum <> Boba ETH (both ways) on staging mainnet
- [ ]  Light bridging - $BOBA can be bridge between BNB <> Boba BNB (both ways) on staging mainnet
- [x]  The history page accurately reflects the txs for all the above cases on staging mainnet

### CODE REVIEW

**Comment by sk-enya** [comment]
@boyuan-chen @wsdt , 

Could you assist me in validating the BNB <> Boba BNB Bridging? I'm unable to test it myself since I don't have any funds in BNB

**Comment by wsdt** [comment]
History page loads infinitely for me.

**Comment by wsdt** [comment]
> @boyuan-chen @wsdt ,
> 
> Could you assist me in validating the BNB <> Boba BNB Bridging? I'm unable to test it myself since I don't have any funds in BNB

just tried again, the history page is stuck for me in infinite loading

**Comment by sk-enya** [comment]
> > @boyuan-chen @wsdt ,
> > Could you assist me in validating the BNB <> Boba BNB Bridging? I'm unable to test it myself since I don't have any funds in BNB
> 
> just tried again, the history page is stuck for me in infinite loading + I have no funds either on Boba BNB/BNB anymore as we have sent everything to the Multisigs.

Transactions are loading correctly from me on the history page you can verify on staging.

**Review by boyuan-chen — APPROVED** [review]

**Pull request merged**
