### PR TITLE
feat: Move GraphQL Service out of Gateway into separate package

### PR DESCRIPTION
**Pull request by wsdt**
# Changes
- GraphQL Service moved out into separate package to have lightbridge backend and gateway synced. 

FYI @souradeep-das

### CODE REVIEW

**Comment by souradeep-das** [comment]
great, please also add branch protections for `graphql-utils` repo!

**Review by sk-enya — APPROVED** [review]
Looks good!

**Comment by sk-enya** [comment]
@wsdt Is there any specific reason to move this service to the utility?

**Comment by wsdt** [comment]
> @wsdt Is there any specific reason to move this service to the utility?

Yes because the lightbridge backend service & gateway both need to read via graphql from the smart contracts (and this way we have it in one place and avoid maintenance overhead)

**Pull request merged**
