### PR TITLE
Refactory Modals to ts + removing material ui

### PR DESCRIPTION
**Pull request by alvaro-ricotta**
This commit involves changes on the following modals : 

DelegateDaoModal
NewProposalModal
NetworkPicker
DaoModal
NoMetamaskModal
SettingsModal
StakeModal
SwitchNetworkModal
TransactionSuccessModal
UnsupportedNetworkModal
BridgeConfirmModal

### CODE REVIEW

**Comment by sk-enya** [comment]
@alvaro-ricotta Just a comment can you please move all js to typescript for the component at least.

Last but not least please add integration/unit test it's quite easy now to add as the setup is already ready for us.

**Comment by sk-enya** [comment]
@alvaro-ricotta please make sure to add reviewer whenever you create new PR.

**Comment by sk-enya** [comment]
@alvaro-ricotta closing this as you are creating new PRs against this.

**Comment by alvaro-ricotta** [comment]
@sk-enya i´ll close this after i finish all the migration!

**Comment by sk-enya** [comment]
Opps sorry I closed this earlier itself but anyways your feel free to reopen.

**Pull request closed without merging**
